- name: Setting variables' values 
  hosts: all
  gather_facts: true
  vars:
   ansible_ssh_user : "{{ lookup('env','TF_VAR_VM_USER') }}"
   ansible_ssh_private_key_file : "{{ lookup('env','TF_VAR_VM_SSH_KEY_FILE') }}"
   tunnel_type : "{{ lookup('env','TUNNEL_TYPE') }}"

  tasks:
  - name: "remove hosts from known_hosts"
    local_action:
      known_hosts
      path=known_hosts
      name='{{inventory_hostname}}'
      state=absent
     
  - name: print out the hostname of target
    command: hostname
  
  - name: print working directory
    command: pwd
      
  - name: Creating tunnels
    shell: |
     sudo ovs-vsctl add-port l2-br {{ tunnel_id }} -- set interface {{ tunnel_id }} type={{ tunnel_type }} options:remote_ip={{ remote_ip }} options:psk=123456789
      
